name: GemstoneClasses
version: 1.0.0
main: com.starshootercity.gemstoneclasses.GemstoneClasses
description: Origins-Reborn addon adding classes based on gemstones
api-version: '1.20'
author: cometcake575

depend:
  - Origins-Reborn
